eval:
    n_perturbations: 2
    seed: 42
benchmark:
    path: consistent_agents.benchmarks.swebench.swebench_benchmark:SWEBenchBenchmark
    params:
      split: "test[:3]"
metrics:
  - path: consistent_agents.metrics.swebench:SWEBenchMetric
    name: swebench
    params: {}
agent:
    path: consistent_agents.agents.default:DefaultAgent
    params:
      config_class_name: default
    model:
        path: consistent_agents.models.litellm:LitellmModel
        params:
          model_name: openai/gpt-4o-mini
          model_kwargs:
            temperature: 0.1
            max_tokens: 5000
perturbations:
  - path: consistent_agents.perturbations.paraphrase:LLMParaphrasePerturbation
    name: paraphrase
    params:
      seed: 42
  - path: consistent_agents.perturbations.translation:LLMBackTranslationPerturbation
    name: translation
    params:
      seed: 42
  - path: consistent_agents.perturbations.injection:LLMInjectionPerturbation
    name: injection
    params:
      seed: 42
output:
    path: outputs/swebench.json
