eval:
    n_perturbations: 2
    seed: 42
benchmark:
    path: consistent_agents.benchmarks.swebench.swebench_benchmark:SWEBenchBenchmark
    params:
      split: "test[:1]"
metrics:
  - path: consistent_agents.metrics.accuracy:AccuracyMetric
    name: accuracy
    params:
      judge_model: "gpt-4o-mini"
  - path: consistent_agents.metrics.consistency:ConsistencyMetric
    name: consistency
    params:
      judge_model: "gpt-4o-mini"
agent:
    path: consistent_agents.agents.default:DefaultAgent
    params:
      config_class_name: default
    model:
        path: consistent_agents.models.litellm:LitellmModel
        params:
          model_name: gpt-5-mini
          model_kwargs:
            temperature: 1
            max_tokens: 1600
perturbations:
  - path: consistent_agents.perturbations.injection:LLMInjectionPerturbation
    name: injection
    params:
      seed: 42
output:
    path: outputs/swebench.json