eval:
    n_perturbations: 3
    seed: 42
benchmark:
    path: consistent_agents.benchmarks.truthfulqa:TruthfulQABenchmark
    params:
      split: "validation[:5]"
agent:
    path: consistent_agents.agents.default:DefaultAgent
    params:
      config_class_name: default
    model:
        path: consistent_agents.models.litellm:LitellmModel
        params:
          model_name: gpt-4o-mini
          model_kwargs:
            temperature: 0.1
            max_tokens: 300
    environment:
        path: consistent_agents.environments.docker:DockerEnvironment
        params:
          name: my_local
perturbations:
  - path: consistent_agents.perturbations.paraphrase:LLMParaphrasePerturbation
    name: paraphrase
    params:
      noise_level: 0.08
      seed: 42
output:
    path: outputs/truthfulqa_paraphrase.json